# Generated by Django 5.1 on 2025-03-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_task_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('Bug', 'Bug'), ('Feature', 'Feature'), ('Improvement', 'Improvement'), ('Research', 'Research')], default='Feature', max_length=20, null=True),
        ),
    ]
